Repository aniketsinha2002/DataGeek, pull requests merged in 2023-05, with the labels that each got.

#270 back to top button added
  css/style.css
  index.html
  main.js
Labels: gssoc23, level3

#301 Just added mailto and tel link to mail and mobileno
  course.html
  index.html
Labels: gssoc23, level1

#348 Updated readme
  README.md
  images/gssoc.jpg
  images/repo.png
Labels: gssoc23, level2
